title: Campfire Guide

remote_theme: pmarsceill/just-the-docs
logo: "/assets/images/campfire-guide-side-logo.png"
heading_anchors: true

permalink: pretty
exclude:
  [
    "node_modules/",
    "*.gemspec",
    "*.gem",
    "Gemfile",
    "Gemfile.lock",
    "package.json",
    "package-lock.json",
    "script/",
    "LICENSE.txt",
    "lib/",
    "bin/",
    "README.md",
    "Rakefile",
  ]
