title: Volaby Guide

remote_theme: pmarsceill/just-the-docs
logo: "/assets/images/campfire-guide-side-logo.png"
heading_anchors: true

ga_tracking: UA-149024912-4
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true by default)

permalink: pretty
exclude:
  [
    "node_modules/",
    "*.gemspec",
    "*.gem",
    "Gemfile",
    "Gemfile.lock",
    "package.json",
    "package-lock.json",
    "script/",
    "LICENSE.txt",
    "lib/",
    "bin/",
    "README.md",
    "Rakefile",
  ]
